# only run for: merge commits, releases and pull-requests
if: branch =~ ^\d+\.\d+\.\d+$

stages:
  - name: deploy

os: osx
language: swift
osx_image: xcode11.6
  
jobs:
  include:
    - stage: deploy
      name: Jazzy
      before_install: |
        cat <<\ \ EOF> .jazzy.yaml
        module: Version
        module_version: TRAVIS_TAG
        custom_categories:
          - name: Version
            children:
              - Version
        xcodebuild_arguments:
          - UseModernBuildSystem=NO
        output: output
        github_url: https://github.com/mxcl/Version
        EOF
        sed -i '' "s/TRAVIS_TAG/$TRAVIS_TAG/" .jazzy.yaml
      # ^^ this weirdness because Travis multiline YAML is broken and inserts
      # two spaces in front of the output which means we need a prefixed
      # delimiter which also weirdly stops bash from doing variable substitution
      install: gem install jazzy
      before_script: swift package generate-xcodeproj
      script: jazzy
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: output
        on:
          tags: true
