on:
  push:
    branches:
      - master
    paths:
      - Sources/**
      - Tests/**
jobs:
  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift --version
    - run: swift test --parallel
