name: CI

on:
  pull_request:
    paths:
      - Sources/**
      - Tests/**
      - .github/workflows/ci.yml
  push:
    branches: master
    paths: .github/workflows/ci.yml
  schedule:
    - cron: '3 3 * * 4'  # 3:03 AM, every Thursday

concurrency:
  group: ${{ github.head_ref || 'scheduled' }}
  cancel-in-progress: true

jobs:
  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift test --parallel

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
          - '4.2'
          - '5.0'
          - '5.1'
          - '5.2'
          - '5.3'
    container:
      image: swift:${{ matrix.swift }}
    steps:
    - uses: actions/checkout@v2
    - run: swift build

  code-coverage:
    runs-on: ubuntu-latest
    name: linux (5.4)
    container:
      image: swift:5.4
    continue-on-error: true  #continuous-resilience
    steps:
    - uses: actions/checkout@v2
    - run: swift test --parallel --enable-code-coverage
    - run: |
        apt-get -qq update
        apt-get -qq install curl
      # ^^ for codecov’s action 🙄
    - run: |
        b="$(swift build --show-bin-path)"
        llvm-cov export \
            -format lcov \
            -instr-profile="$b/codecov/default.profdata" \
            --ignore-filename-regex='\.build|Tests' \
            "$b"/*.xctest \
          > info.lcov
    - uses: codecov/codecov-action@v1
      with:
        file: ./info.lcov
